version: '3.8'
services:
  # links_preview:
  #   build: .
  #   ports:
  #     - \"8080:8080\"
  app:
    platform: linux/amd64
    build: .
    container_name: links_preview
    ports:
      - "8081:8081"
    restart: unless-stopped